### ISSUE TITLE
Compatibility issues with TronLink extension

### ISSUE THREAD

**Issue by amirhossein-fzl** [spatie/laravel-ignition#68] opened 2022-03-07 07:17 UTC
- Laravel Version: 9.3.1
- PHP Version: 8.0.15
- Database Driver & Version: mysql, 5.7.33
- Google Cgrome: 99.0.4844.51

Hello. When I get an error in Laravel, when I scroll the page or click on any of the links on the error page, the page appears as follows.

![ignition 00_00_00-00_00_30](https://user-images.githubusercontent.com/53816722/156985095-149eb60d-36bd-47c5-8565-ae6fd113efcb.gif)

The browser console also shows this error !!

![issue](https://user-images.githubusercontent.com/53816722/156985315-eb779cb3-ac7b-4058-aaa4-bc14ce82ff8b.png)

**Comment by AlexVanderbist** [comment] 2022-03-08 10:51
Hi, thanks for reporting this issue. Can you share the exact spatie/ignition and spatie/laravel-ignition versions with us? 

You can find those by running `composer show spatie/ignition` and `composer show spatie/laravel-ignition` and looking at the `versions` section.

**Comment by amirhossein-fzl** [comment] 2022-03-08 14:19
> composer show spatie/ignition

Hi.

- spatie/ignition version: 1.0.5
- spatie/laravel-ignition version: 1.0.6

**Comment by AlexVanderbist** [comment] 2022-03-08 14:22
Hi @amirhossein-fzl, can you try updating your composer dependencies by running `composer update` please? We've added error boundaries in `spatie/ignition:1.1.0` which should hopefully catch the error and help us solve this issue for you :)

**Comment by amirhossein-fzl** [comment] 2022-03-08 14:38
> composer update

I ran the `composer update` command and did the update. But the error was not fixed !!

![image](https://user-images.githubusercontent.com/53816722/157259592-1165ba5e-1e2a-4d1e-a936-b8d31ed8aeb9.png)

**Comment by AlexVanderbist** [comment] 2022-03-08 15:00
Can you share that URL from the error message in the console here? It'll include the specific error that we're looking for

**Comment by amirhossein-fzl** [comment] 2022-03-09 09:55
> Can you share that URL from the error message in the console here? It'll include the specific error that we're looking for

Yes

http://music-app.test/admin/profile (localhost)

No hashtags are created in the URL. I deliberately created this error to show you the problem. Otherwise I am currently working on my project with Firefox to temporarily solve my problem. You can also see this problem in Google Chrome browser and try to solve it. Thanks 🙏

**Comment by AlexVanderbist** [comment] 2022-03-09 10:40
Hey @amirhossein-fzl, can you please share the full reactjs.org URL that you showed in the developer tools console error?

This one in here: 
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/6287961/157425527-72751ce6-f2bb-47f6-8232-91349a81d86b.png">

I can't seem to locally replicate the issue on my version of Chrome so we'll need some more context

**Comment by amirhossein-fzl** [comment] 2022-03-09 14:10
> Hey @amirhossein-fzl, can you please share the full reactjs.org URL that you showed in the developer tools console error?
> 
> This one in here: <img alt="image" width="1238" src="https://user-images.githubusercontent.com/6287961/157425527-72751ce6-f2bb-47f6-8232-91349a81d86b.png">
> 
> I can't seem to locally replicate the issue on my version of Chrome so we'll need some more context

https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=symbol&args[]=

**Comment by AdrianMrn** [comment] 2022-03-10 15:22
@amirhossein-fzl We've tried but still can't reproduce this. Could you create a minimal reproduction repository where can see this error happening in Chrome please?

**Comment by amirhossein-fzl** [comment] 2022-03-10 15:28
> @amirhossein-fzl We've tried but still can't reproduce this. Could you create a minimal reproduction repository where this error happens please?

No. My project is private and it is not possible for me. You mean, like, your Google Chrome does not show this error? If so, I will reinstall my browser. Maybe the problem is with my browser

**Comment by ebiboy2** [comment] 2022-03-14 00:10
I can create a minimal reproduction repository if you still want. I am currently facing the same issue.

**Comment by AdrianMrn** [comment] 2022-03-15 10:34
@ebiboy2 Yes please 🙏

**Comment by tfevan** [comment] 2022-03-16 05:07
Here another error posted on stackoverflow https://stackoverflow.com/questions/71492001/laravel-errors-disappears-ignition

[![Attaching a gif of the entire issue][1]][1]


  [1]: https://i.stack.imgur.com/7YsKk.gif

**Comment by AdrianMrn** [comment] 2022-03-16 08:49
@tfevan As mentioned, we haven't been able to reproduce this bug and are still hoping for someone to create a **minimal public repository** where we can reproduce this error.

Without any extra information on how to reproduce this bug, we're shooting in the dark and have no way to solve this bug.

**Comment by ebiboy2** [comment] 2022-03-16 09:50
Kindly check out this repo https://github.com/ebiboy2/laravel-MinifiedReactError to reproduce the error

Laravel Framework 9.3.1
Chrome Version 99.0.4844.74 (Official Build) (64-bit)

I can provide any other information you might need. Just ask

**Comment by AdrianMrn** [comment] 2022-03-16 10:49
@ebiboy2 Thanks a bunch for the repo. I've installed it and I'm not getting the bug :(

Could you please try opening the page in an incognito window (which should disable all your browser extensions), and see if that changes anything? If the bug disappears, could you disable all your extensions and enable them 1 by 1 to see which one could be causing the issue?

If the bug still happens in incognito, please let me know and we'll continue looking from there.

**Comment by amirhossein-fzl** [comment] 2022-03-16 10:57
In incognito window (when add-ons are disabled), this problem is fixed. This error occurs if there is an interference between Google Chrome add-ons and the disruptive plugin must be found.

The reason I did not have this problem with the Firefox add-on was that my Firefox did not have any add-ons.

**Comment by AdrianMrn** [comment] 2022-03-16 12:22
We can reproduce the bug when the TronLink extension is enabled. We'll let you know once we've found a solution. For now, see if you can disable the extension from running on your test domains or use a different browser.

**Comment by tfevan** [comment] 2022-03-16 13:16
> Kindly check out this repo https://github.com/ebiboy2/laravel-MinifiedReactError to reproduce the error

Just installed the repo, but I'm not getting any error, I'm on Windows Chrome Version 99.0.4844.74 and my PHP is 8.0.6

I'm gonna install TronLink now  and let you know

**Comment by ebiboy2** [comment] 2022-03-16 14:56
Incognito mode seem to solve the problem.
BTW i have TronLink extension installed which i think causes the problem.

**Comment by desyashasyi** [comment] 2022-03-16 18:21
I have some problem in production.

Ubuntu 20.04-NGINX
`"php": "^8.1.3",
        "apereo/phpcas": "1.4.0",
        "awobaz/compoships": "^2.1",
        "barryvdh/laravel-dompdf": "^1.0",
        "guzzlehttp/guzzle": "^7.2",
        "intervention/image": "^2.7",
        "jeroennoten/laravel-adminlte": "^3.8",
        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "laravel/ui": "^3.4",
        "livewire/livewire": "^2.10",
        "maatwebsite/excel": "^3.1",
        "mhmiton/laravel-modules-livewire": "^1.5",
        "nwidart/laravel-modules": "^9.0",
        "realrashid/sweet-alert": "^5.0",
        "santigarcor/laratrust": "^7.0",
        "subfission/cas": "4.2.0"`
        
        
![image](https://user-images.githubusercontent.com/48233515/158659201-610c638d-7ca6-4d92-a5db-b59b226b05ac.png)


Howwever, I can run it normally in local developmen on Mac with same configuration

![image](https://user-images.githubusercontent.com/48233515/158659405-e5b1bde3-27b4-457e-92ae-55b3b205bd11.png)


I found that page problem appeared due to permission of laravel.log file. After  I gave permissio, the error page working normally.

![image](https://user-images.githubusercontent.com/48233515/158660416-8df0ea38-7dc4-46ba-ac80-0bf827b318e9.png)

**Comment by AlexVanderbist** [comment] 2022-03-19 13:13
Hi @desyashasyi, are you also using the TronLink extension? If not, can you please open a new issue about the laravel.log permission problem? Thanks!

**Comment by AlexVanderbist** [comment] 2022-04-24 12:29
Hi all, I just tried to install the TronLink extension again to check if the issue still exists but it seems to have been resolved in a previous update. If anyone is still experiencing compatibility issues with TronLink (or inexplicable page crashes when scrolling) feel free to open a new issue. Thanks!

**Closed by AlexVanderbist** 2022-04-24 12:29 UTC
